---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
