---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
